apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: aromatics-gateway
  namespace: aromatics
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-gateway
  namespace: aromatics
spec:
  hosts:
  - "*"
  gateways:
  - aromatics-gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: api-gateway
        port:
          number: 8080
