server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: identity-route
          uri: lb://identity-service   # lb:// = load balancing qua Eureka
          predicates:
            - Path=/api/identity/**
          filters:
            - RewritePath=/api/identity/(?<segment>.*), /$\{segment}

        - id: catalog-route
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog/**
          filters:
            - RewritePath=/api/catalog/(?<segment>.*), /$\{segment}

        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/order/(?<segment>.*), /$\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/